### PR TITLE
Slash (hybrid) commands

### PR DESCRIPTION
**Pull request by TCAtrevor**
i think its good to merge now probably

### CODE REVIEW

**Comment by aleeeuwu** [comment]
are you sure

**Comment by TCAtrevor** [comment]
i think everything doesn't not work

**Comment by aleeeuwu** [comment]
i will give you 2 minutes to change your decision

**Comment by TCAtrevor** [comment]
whats wrong!!

**Comment by aleeeuwu** [comment]
nothing i just want you to be sure

**Comment by TCAtrevor** [comment]
alright I will say this with more confidence

everything doesn't not work

**Pull request merged**
