### PR TITLE
Divided management commands on one file

### PR DESCRIPTION
**Pull request by aleeeuwu**
I think everything works but maybe you find an issue or something else to find to the files

### CODE REVIEW

**Comment by aleeeuwu** [comment]
Btw I also put the ban command into the classicCommands file and deleted the ban.py file

Feel free to add anything else to the branch or move any other command around and tell me when you think it's ready to merge

**Comment by TCAtrevor** [comment]
swag

**Comment by aleeeuwu** [comment]
does swag mean you think its fine?

**Comment by TCAtrevor** [comment]
yeah

**Comment by aleeeuwu** [comment]
im merging now then its your fault if something breaks!!!!

**Pull request merged**
