### PR TITLE
Linux compatibility

### PR DESCRIPTION
**Pull request by kittrz9**
certain commands like wget and dir don't work when running linux (or at least doesn't work for me) because it relies on powershell. since the bot is ran through WSL it _should_ still work but I'm not 100% sure and I don't really know of a good way for me to test it.

### CODE REVIEW

**Comment by TCAtrevor** [comment]
we run it natively on Windows actually which is why all the subprocess stuff is set up weird, like the neofetch command that launches WSL just to run the command and then return the output to python. We should probably look for some python modules that can work universally, or in some cases we can just do something like replacing `wget` with `curl` since Windows and Linux (and macOS) have a native version of that built in usually.

**Comment by kittrz9** [comment]
oh, that's weird lmao, I thought it was running just on WSL from the neofetch output. I didn't know that was why it was running bash and then running neofetch from that
it might be a good idea though to just start fully running it on WSL in case you want to run it on a VPS or just to have it not be as weird, though I understand if you want to keep it that way
idk if I should close this then or what

**Comment by TCAtrevor** [comment]
Im working on making every subprocess command use bash so that it can work on every system.

**Comment by TCAtrevor** [comment]
the only issue now is that the slash commands give that one weird 404 before working but it does technically work so I guess we will wait for Ale.

**Comment by kittrz9** [comment]
I'm not getting the 404 error when running it on linux anymore so maybe it's another issue with using wsl like this

**Pull request merged**
